name: Deploy to AWS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1               # or your region
  ECR_REPOSITORY: my-backend-repo     # ECR repo name
  ECS_CLUSTER: backend-cluster        # ECS cluster name
  ECS_SERVICE: backend-service        # ECS service name
  S3_BUCKET: my-frontend-bucket       # S3 bucket for frontend assets

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---------- Backend image ----------
      - name: Build backend image
        run: |
          docker build -t $ECR_REPOSITORY:latest backend
          docker tag $ECR_REPOSITORY:latest \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push backend image to ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION

      # ---------- Frontend assets ----------
      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/dist s3://$S3_BUCKET --delete
